language: node_js
node_js:
  - "10.15.0"
cache:
  directories:
  - node_modules #Cache node_modules for faster builds
script:
  - npm test #Runs Tests
  - npm run build #Creats a production build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master